### PR TITLE
Updating the Button component to allow aria-* attributes and…

### PR DESCRIPTION
**Pull request by EdwinGuzman**
… updating the styles.
Resolves [SIMPLY-2139](https://jira.nypl.org/browse/SIMPLY-2139).

### CODE REVIEW

**Comment by adriana-alter** [comment]
Maybe easier to implement if, instead of each aria attribute being passed to the Button separately, you could pass in a dictionary of key/value pairs as a designated aria attributes prop?

Otherwise, looks good!

**Comment by EdwinGuzman** [comment]
Hmm maybe like
```
const aria = {
  selected: true,
  pressed: true,
  label: "some aria label"
};

<Button .... aria={aria} />
```
? I think that's adding more complexity, especially if you only want to add one attribute. It also doesn't allow you to use other attributes like `autofocus` or `data-*` (if they are ever needed).

**Comment by adriana-alter** [comment]
What about a dictionary of extra attributes, then (that you could use for aria plus whatever else)?  It just seems a lot easier not to have to pass everything in individually...

**Comment by adriana-alter** [comment]
We may be talking about different things; I meant that the Button would have an `extraProps` prop, which would be put together by whatever parent component was importing and using the Button, not actually in the Button itself (like `<Button extraProps={} />`), and the Button would just merge it into the other props (like is already happening on line 34).  (Maybe still not worth it, though!)

**Comment by EdwinGuzman** [comment]
That makes sense, but `...rest` and `extraprops` when destructuring would have the same effect except for the name (and I prefer to use the native pattern). And you're still having the parent component make an extra step to combine the props. It seems easier to me to just make them add props to the components which one is already use to.

**Pull request merged**
